// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_objects.proto

package reactor.io.encoding.protobuf;

public final class TestObjects {
  private TestObjects() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface RichObjectOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // required float percent = 2;
    /**
     * <code>required float percent = 2;</code>
     */
    boolean hasPercent();
    /**
     * <code>required float percent = 2;</code>
     */
    float getPercent();

    // required int64 total = 3;
    /**
     * <code>required int64 total = 3;</code>
     */
    boolean hasTotal();
    /**
     * <code>required int64 total = 3;</code>
     */
    long getTotal();
  }
  /**
   * Protobuf type {@code reactor.io.encoding.protobuf.RichObject}
   */
  public static final class RichObject extends
      com.google.protobuf.GeneratedMessage
      implements RichObjectOrBuilder {
    // Use RichObject.newBuilder() to construct.
    private RichObject(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private RichObject(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final RichObject defaultInstance;
    public static RichObject getDefaultInstance() {
      return defaultInstance;
    }

    public RichObject getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private RichObject(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              percent_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              total_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return reactor.io.encoding.protobuf.TestObjects.internal_static_reactor_io_encoding_protobuf_RichObject_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return reactor.io.encoding.protobuf.TestObjects.internal_static_reactor_io_encoding_protobuf_RichObject_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              reactor.io.encoding.protobuf.TestObjects.RichObject.class, reactor.io.encoding.protobuf.TestObjects.RichObject.Builder.class);
    }

    public static com.google.protobuf.Parser<RichObject> PARSER =
        new com.google.protobuf.AbstractParser<RichObject>() {
      public RichObject parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RichObject(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RichObject> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required float percent = 2;
    public static final int PERCENT_FIELD_NUMBER = 2;
    private float percent_;
    /**
     * <code>required float percent = 2;</code>
     */
    public boolean hasPercent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required float percent = 2;</code>
     */
    public float getPercent() {
      return percent_;
    }

    // required int64 total = 3;
    public static final int TOTAL_FIELD_NUMBER = 3;
    private long total_;
    /**
     * <code>required int64 total = 3;</code>
     */
    public boolean hasTotal() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 total = 3;</code>
     */
    public long getTotal() {
      return total_;
    }

    private void initFields() {
      name_ = "";
      percent_ = 0F;
      total_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPercent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTotal()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, percent_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, total_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, percent_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, total_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static reactor.io.encoding.protobuf.TestObjects.RichObject parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static reactor.io.encoding.protobuf.TestObjects.RichObject parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static reactor.io.encoding.protobuf.TestObjects.RichObject parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static reactor.io.encoding.protobuf.TestObjects.RichObject parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static reactor.io.encoding.protobuf.TestObjects.RichObject parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static reactor.io.encoding.protobuf.TestObjects.RichObject parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static reactor.io.encoding.protobuf.TestObjects.RichObject parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static reactor.io.encoding.protobuf.TestObjects.RichObject parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static reactor.io.encoding.protobuf.TestObjects.RichObject parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static reactor.io.encoding.protobuf.TestObjects.RichObject parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(reactor.io.encoding.protobuf.TestObjects.RichObject prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code reactor.io.encoding.protobuf.RichObject}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements reactor.io.encoding.protobuf.TestObjects.RichObjectOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return reactor.io.encoding.protobuf.TestObjects.internal_static_reactor_io_encoding_protobuf_RichObject_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return reactor.io.encoding.protobuf.TestObjects.internal_static_reactor_io_encoding_protobuf_RichObject_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                reactor.io.encoding.protobuf.TestObjects.RichObject.class, reactor.io.encoding.protobuf.TestObjects.RichObject.Builder.class);
      }

      // Construct using reactor.io.encoding.protobuf.TestObjects.RichObject.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        percent_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        total_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return reactor.io.encoding.protobuf.TestObjects.internal_static_reactor_io_encoding_protobuf_RichObject_descriptor;
      }

      public reactor.io.encoding.protobuf.TestObjects.RichObject getDefaultInstanceForType() {
        return reactor.io.encoding.protobuf.TestObjects.RichObject.getDefaultInstance();
      }

      public reactor.io.encoding.protobuf.TestObjects.RichObject build() {
        reactor.io.encoding.protobuf.TestObjects.RichObject result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public reactor.io.encoding.protobuf.TestObjects.RichObject buildPartial() {
        reactor.io.encoding.protobuf.TestObjects.RichObject result = new reactor.io.encoding.protobuf.TestObjects.RichObject(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.percent_ = percent_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.total_ = total_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof reactor.io.encoding.protobuf.TestObjects.RichObject) {
          return mergeFrom((reactor.io.encoding.protobuf.TestObjects.RichObject)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(reactor.io.encoding.protobuf.TestObjects.RichObject other) {
        if (other == reactor.io.encoding.protobuf.TestObjects.RichObject.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasPercent()) {
          setPercent(other.getPercent());
        }
        if (other.hasTotal()) {
          setTotal(other.getTotal());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (!hasPercent()) {
          
          return false;
        }
        if (!hasTotal()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        reactor.io.encoding.protobuf.TestObjects.RichObject parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (reactor.io.encoding.protobuf.TestObjects.RichObject) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // required float percent = 2;
      private float percent_ ;
      /**
       * <code>required float percent = 2;</code>
       */
      public boolean hasPercent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required float percent = 2;</code>
       */
      public float getPercent() {
        return percent_;
      }
      /**
       * <code>required float percent = 2;</code>
       */
      public Builder setPercent(float value) {
        bitField0_ |= 0x00000002;
        percent_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required float percent = 2;</code>
       */
      public Builder clearPercent() {
        bitField0_ = (bitField0_ & ~0x00000002);
        percent_ = 0F;
        onChanged();
        return this;
      }

      // required int64 total = 3;
      private long total_ ;
      /**
       * <code>required int64 total = 3;</code>
       */
      public boolean hasTotal() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 total = 3;</code>
       */
      public long getTotal() {
        return total_;
      }
      /**
       * <code>required int64 total = 3;</code>
       */
      public Builder setTotal(long value) {
        bitField0_ |= 0x00000004;
        total_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 total = 3;</code>
       */
      public Builder clearTotal() {
        bitField0_ = (bitField0_ & ~0x00000004);
        total_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:reactor.io.encoding.protobuf.RichObject)
    }

    static {
      defaultInstance = new RichObject(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:reactor.io.encoding.protobuf.RichObject)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_reactor_io_encoding_protobuf_RichObject_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_reactor_io_encoding_protobuf_RichObject_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022test_objects.proto\022\034reactor.io.encodin" +
      "g.protobuf\":\n\nRichObject\022\014\n\004name\030\001 \002(\t\022\017" +
      "\n\007percent\030\002 \002(\002\022\r\n\005total\030\003 \002(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_reactor_io_encoding_protobuf_RichObject_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_reactor_io_encoding_protobuf_RichObject_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_reactor_io_encoding_protobuf_RichObject_descriptor,
              new java.lang.String[] { "Name", "Percent", "Total", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
