[[recipe-filestream]]
=== Building a simple File Stream

Let's start with a pure `Publisher` implementation, we'll use Reactor API afterwads to simplify the following example.
As `Publisher` you will have to take care about a lot of small things that should be tested against the *Reactive Streams* TCK module. The purpose is to understand what *Reactor* can do for you in such situation:

.Build a lazy file read Publisher matching the Subscriber request
[source, java, indent=2]
----
Publisher<String> fileStream = new Publisher<String>() { // <1>
	@Override
	public void subscribe(final Subscriber<? super String> subscriber) {
		final File file = new File("settings.gradle"); // <2>

		try {
			final BufferedReader is = new BufferedReader(new FileReader(file)); // <2>

			subscriber.onSubscribe(new Subscription() {

				final AtomicBoolean terminated = new AtomicBoolean(false);

				@Override
				public void request(long n) {
					long requestCursor = 0l;
					try {
						String line;
						while ((requestCursor++ < n || n == Long.MAX_VALUE) // <3>
								&& !terminated.get()) { // <4>
						
							line = is.readLine();
							if (line != null) {
								subscriber.onNext(line);
							} else 
								if(terminate()){									
									subscriber.onComplete(); // <5>
								}
								return;
							}
						}
					} catch (IOException e) {
						if (terminate()){
							subscriber.onError(e); // <6>
						}
					}
				}

				@Override
				public void cancel() {
					terminate();
				}

				private boolean terminate(){
					if(terminated.compareAndSet(false, true)){
						try {
							is.close(); // <7>							
						} catch(Exception t) {
							subscriber.onError(t);
						}
						return true;
					}
					return false;
				}
			});

		} catch (FileNotFoundException e) {
			Streams.<String, FileNotFoundException> fail(e)
				.subscribe(subscriber); // <8>
		}
	}
};

Streams.wrap(fileStream)
	.capacity(4L) // <9>
	.consumeOn( // <10>
		Environment.sharedDispatcher(),
		System.out::println,
		Throwable::printStackTrace,
		nothing -> System.out.println("## EOF ##")
);

----
<1> Implement a `Publisher`. We'll see in the next example how to be smart about it with core and stream
<2> Open a `File` cursor and reader by Subscriber to allow for replayability: It's a `Cold Stream`.
<3> Match the number of read lines with the demand and ignore the demand if special Long.MAX_VALUE escaping number is passed.
<4> Check before each possible `onNext()` if the Stream is not *cancelled*.
<5> Call `onComplete()` which set the state of the `Subscription` to *cancelled*, ignoring further terminal signal if any.
<6> Call `onError(e)` which set the state of the `Subscription` to *cancelled*, ignoring further terminal signal if any. 
<7> Close the file if the subscriber is not interested any more in the content (error, completion, cancel). 
<8> Create a failed `Stream` that only `onSubscribe()` the pass subscriber and `onError(e)` it.
<9> `capacity` will hint downstream operations (`consumeOn` here) to chunk requests 4 by 4.
<10> `consumeOn` takes an extra argument to run the requests on a dispatcher in addition to the 3 possible `Consumer` reacting to each type of signal.

Obviously there are ways to make that code more efficient, but also do more with less. Let's take a look at Reactor alternative `PublisherFactory` from core module, which is used by `Streams.createWith()` methods from stream module.


.Build a lazy file read with Streams.createWith (PublisherFactory based) machinery (from 2.0.2+)
[source, java, indent=2]
----
Stream<String> fileStream = Streams.createWith( 
	(n, sub) -> { // <1>
		String line;
		final BufferedReader inputStream = sub.context() // <2>		
		long requestCursor = 0l;
		while ((requestCursor++ < n || n == Long.MAX_VALUE) && !sub.isCancelled()) { // <3>
			
			line = inputStream.readLine();
			if (line != null) {
				sub.onNext(line);
			} else {
				sub.onComplete(); // <4>
				return;
			}								
		}
	}, 
	sub -> new BufferedReader(new FileReader(file)), // <5>
	inputStream -> inputStream.close() // <6>
};

fileStream
	.capacity(4L)
	.consumeOn(
		Environment.sharedDispatcher(),
		System.out::println,
		Throwable::printStackTrace,
		nothing -> System.out.println("## EOF ##")
);

----
<1> Implement a `BiConsumer` to react on every `Subscriber` request `Long` n. Any unchecked exception will trigger the terminal callback and `Subscriber.onError(e)`.
<2> The `Subscriber` passed in the callback is a `SubscriberWithContext` decorator allowing access to `context()`  populated on start
<3> Match the number of read lines with the demand and ignore the demand if special Long.MAX_VALUE escaping number is passed. Also use `SubscriberWithContext.isCancelled()` to check asynchronous cancel from `Subscribers` before each read.
<4> Call `onComplete()` which set the state of the `SubscriberWithContext` to *cancelled*, ignoring further terminal signal if any.
<5> Define a context once for a new `Subscriber` that will be available later for each request `SubscriberWithContext.context()` 
<6> Define a terminal callback once intercepting `cancel()`, `onComplete()` or `onError(e)`.

We can use `PublisherFactory`, or <<streams.adoc#streams-basics, Streams factories>> like `Streams.createWith()` to quickly achieve common use cases:

* Open IO once
* React on requests
* Handle shutdown gracefully

=== Building Efficient Data Pipelines

=== Building Non-Blocking MicroServices

=== Building CQRS-like Applications

=== Other Example Applications

[horizontal]
https://github.com/reactor/reactor-quickstart[Quickstart]::
An example application showing several ways to use basic components in Reactor.
https://github.com/reactor/reactor-samples[Samples]::
A simple sample application that demonstrates Reactor functionality in JUnit tests.